[package]
name = "snmptrap-snatch"
version = "0.1.0"
authors = ["Haruhiko Uchida <uchida@cnci.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"
snmp-parser = "0.7.0"
